---
#
# Supervisor configuration
#

- name: create supervisor and conf.d under etc>supervisor>conf.d
  file:
    state: directory
    dest: "{{item}}"
    owner: "root"
    group: "root"
    mode: "0755"
  with_items:
   - /etc/supervisor
   - /etc/supervisor/conf.d

- name: Copy supervisord.conf.j2 from template to etc>supervisor>supervisord.conf
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "root"
    group: "root"
    mode: "0755"
  with_items:
   - { src: templates/etc/supervisor/supervisord.conf.j2, dest: /etc/supervisor/supervisord.conf }
   - { src: templates/etc/supervisor/conf.d/service.conf.j2, dest: /etc/supervisor/conf.d/service.conf }

#- name: Generate Supervisord config from python script echo_supervisord_conf
#  shell: echo_supervisord_conf > /etc/supervisord.conf

- name: Supervisord initi script copying
  template:
    src: supervisord_init_script_lsb.j2
    dest: "{{supervisord_init_script}}"

#- name: Make init script executable by all
#  shell: chmod a+x "{{supervisord_init_script}}"
#  notify: supervisor restart

- name: Make init script executable by all
  file:
    path: "{{supervisord_init_script}}"
    mode: "a+x"


- name: Add supervisod to services that start on boot
  service:
   name: "{{supervisor_service}}"
   enabled: yes
  notify: supervisor restart
#  notify: supervisor restart

#- name: Supervisor configuration directories
#  file:
#    state=directory
#    dest="{{supervisor_services_dir}}"
#    owner="root"
#    group="root"
#    mode="0755"
#  with_items:
#    - /etc/supervisor
#    - /etc/supervisor/conf.d
#
#- name: Supervisor configuration
#  template:
#    src=etc/supervisor/supervisord.conf.j2
#    dest="{{supervisor_cfg}}"
#    owner="root"
#    group="root"
#    mode="0644"
#  notify: supervisor restart
#
#- name: Supervisor configuration
#  template:
#    src=etc/supervisor/conf.d/service.conf.j2
#    dest="{{supervisor_services_dir}}/{{item.key}}.conf"
#    owner="{{item.value.user|default('root')}}"
#    group="{{item.value.user|default('root')}}"
#    mode="0640"
#  with_dict: "{{supervisor_services}}"
#  notify: supervisor restart

# vi:ts=2:sw=2:et:ft=yaml
