---
#
# Supervisor configuration
#

- name: create supervisor and conf.d under etc>supervisor>conf_d
  file:
    state: directory
    dest: "{{item}}"
    owner: "root"
    group: "root"
    mode: "0755"
  with_items:
   - /etc/supervisor
   - /etc/supervisor/conf_d

- name: Copy supervisord.conf.j2 and welcome.conf.j2 from templates
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "root"
    group: "root"
    mode: "0755"
  with_items:
   - { src: templates/etc/supervisor/supervisord.conf.j2, dest: /etc/supervisor/supervisord.conf }
   - { src: templates/etc/supervisor/conf_d/welcome.conf.j2, dest: /etc/supervisor/conf_d/welcome.conf }

#- name: Generate Supervisord config from python script echo_supervisord_conf
#  shell: echo_supervisord_conf > /etc/supervisord.conf

- name: Supervisord initi script copying
  template:
    src: supervisord_init_red_hat_amzn.j2
    dest: "{{supervisord_init_script}}"

#- name: Make init script executable by all
#  shell: chmod a+x "{{supervisord_init_script}}"
#  notify: supervisor restart

- name: Make init script executable by all
  file:
    path: "{{supervisord_init_script}}"
    mode: "a+x"


- name: Add supervisod to services that start on boot
  service:
   name: "{{supervisor_service}}"
   enabled: yes

- name: start supervisord
  command: supervisord

- name: check status of supervisorctl status
  command: supervisorctl status

# vi:ts=2:sw=2:et:ft=yaml
