---

- name: Amazon pip uninstall supervisor
  pip:
    state: absent
    name: "supervisor"
  when: ansible_distribution == 'Amazon'

- name: cleanup supervisor and conf.d under etc>supervisor>conf_d
  file:
    state: absent
    dest: "{{item}}"
  with_items:
   - /etc/supervisor
   - /etc/init.d/supervisord
   - /var/log/welcome

# vi:ts=2:sw=2:et:ft=yaml
