---
# reverse the supervisord from target machine
# purpose is to make it clean slate
- name: Kill supervisord pid
  shell: kill $(pgrep supervisord) 2> /dev/null
  ignore_errors: yes

- name: Add supervisord to services that start on boot
  command: chkconfig --del supervisord
  ignore_errors: yes

- name: Amazon pip uninstall supervisor
  pip:
    state: absent
    name: "supervisor"
  when: ansible_distribution == 'Amazon'

- name: cleanup supervisor and conf.d under etc>supervisor>conf_d
  file:
    state: absent
    dest: "{{item}}"
  with_items:
   - /etc/supervisor
   - /etc/init.d/supervisord

- name: suggestion to reboot machine now
  debug:
   msg: "reboot your machine to take reversal effect"

# vi:ts=2:sw=2:et:ft=yaml
